#Firebase URL
firebase_url: "https://amber-heat-9132.firebaseio.com/"

keep_files: ['stylesheets', 'js', 'files', 'images']
exclude: ['stylesheets', 'js', 'files', 'images']

rdiscount:
  extensions: [smart]

url: "https://cfms.org"
plugins: [jekyll-paginate, jekyll-paginate-v2]
