#Firebase URL
firebase_url: "https://amber-heat-9132.firebaseio.com/"

keep_files: ['stylesheets', 'js', 'files', 'images/']


repository: schuuly/schuuly.github.io

url: "https://schuuly.github.io"
plugins: [jekyll-paginate, jekyll-paginate-v2]


